name: review

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request
    steps:
      - name: Build and run Docker container
        uses: EzGrade/Pr-Agent-NUWM@main
        env:
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY=${{ github.repository }}
          PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}
          APP_ID=${{ secrets.APP_ID }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL=${{ secrets.OPENAI_MODEL }}
