name: PR Review

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: |
          docker build -t pr-agent-nuwm .
          docker run -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
                     -e GITHUB_REPOSITORY=${{ github.repository }} \
                     -e PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} \
                     -e APP_ID=${{ secrets.APP_ID }} \
                     -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
                     -e OPENAI_MODEL=${{ secrets.OPENAI_MODEL }} \
                     pr-agent-nuwm